services:
  openresty:
    container_name: maas-web
    image: openresty/openresty:alpine-apk
    restart: unless-stopped
    ports:
      - "9001:80"
    volumes:
      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx:rw
      - ./:/app:rw"
  phpfpm:
    image: bitnami/php-fpm:8.2
    container_name: maas-php
    restart: unless-stopped
    volumes:
      - ./:/app:rw
      - ./conf/php-fpm.conf:/opt/bitnami/php/etc/php-fpm.conf
      - ./conf/www.conf:/opt/bitnami/php/etc/php-fpm.d/www.conf
    environment:
      TZ: "Europe/Berlin"
      PHP_MEMORY_LIMIT: "2G"

