version: '3.9'
services:
  php:
    image: webdevops/php-nginx:8.2
    container_name: maas
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=-1
      - PHP_DATE_TIMEZONE = Europe/Berlin
    ports:
      - "80:80"
    volumes:
      - ./:/app:rw,cached
